# Input file with WGS accession numbers downloaded in this study.
accessionNumFile: "config/NCBI_WGS_accessionNumbers.txt"

# profile HMMs for dsrAB
dsrAB_bact_HMMProfile: "config/profileHMM_bacteria_aminoacid.phmm"
dsrAB_arch_HMMProfile: "config/profileHMM_archaea_aminoacid.phmm"

# reference dsrAB files
refMSA: "config/dsrAB_referenceSequences_nucleotide.fasta"

# reference leaves to select from tree
refListToSelect: "config/ref_leaves_to_select.txt"

# BLAST db
blastDB: "workflow/out/sequenceSimilarity/db"

# raxml input files
paramName: "[date]"
binaryModelParams: "workflow/out/modelParams/RAxML_binaryModelParameters."
refTree: "workflow/out/modelParams/RAxML_result."
raxmlOutputFileExtension: "raxml"

scriptsDir: "workflow/scripts"

# conda environments -- requires anaconda. yaml files were extracted from MacOS. Other systems may require different
# dependencies, so if you're not running on MacOS, please install SRA toolkit, Prodigal, and HMMER with anaconda.
sraEnv: "../../workflow/envs/sra-tools.yml"
prodigalEnv: "../../workflow/envs/prodigal_local.yml"
hmmerEnv: "../../workflow/envs/hmmer_local.yml"

# location of SRA repository -- where prefetch sends files to
repositoryDir: "workflow/out/sra_repo/wgs"
# output directory for dumped FASTA files from NCBI
dumpDir: "workflow/out/dump"

# prodigal output directory -- translated genes
prodigalGeneCoordDir: "workflow/out/geneCoord"
prodigalProteinSeqDir: "workflow/out/proteinSeq"

# HMMER search output directories
domtblDir: "workflow/out/dsrAB_hmmer/domtbl"
hmmOutDir: "workflow/out/dsrAB_hmmer/hmmOut"
msaDir: "workflow/out/dsrAB_hmmer/msa"
summaryDir: "workflow/out/dsrAB_hmmer/summary"

# "cleaned" hits -- filtered for score and duplicates -- unique hits
scoreThreshold: 100 # score cutoff
gapThreshold: 60 # gap filter to remove ultra-gappy sequences
cleanHitsDir: "workflow/out/cleanHits"

# Tree files
raxmlOutputDir: "workflow/out/raxmlOutput"
modelParamsDir: "workflow/out/modelParams"
